/*
    Copyright 2020 benerjo

    This file is part of bdmg2k.

    bdmg is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bdmg is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with bdmg.  If not, see <https://www.gnu.org/licenses/>
*/
use crate::{Error, Object, ObjectDB};

use std::io::prelude::*;
use std::path::PathBuf;

///Create the diesel schema for the object database
pub fn write_schema(object_db: &ObjectDB, destination: &str) -> Result<(), Error> {
    let pbuf = PathBuf::from(destination);

    if !pbuf.exists() {
        match std::fs::create_dir(&pbuf) {
            Ok(()) => {}
            Err(e) => {
                return Err(Error::UnableToCreateOutputDirectory {
                    destination: destination.to_string(),
                    error: e,
                })
            }
        }
    }

    if !pbuf.is_dir() {
        return Err(Error::DestinationIsNotDirectory {
            destination: String::from(destination),
        });
    }

    let content = generate_schema(object_db);

    let (mut sql_file, filename) = super::get_file(&pbuf, "schema", "rs")?;

    match sql_file.write(content.as_bytes()) {
        Err(_e) => {
            return Err(Error::UnableToWriteToFile {
                file: filename,
                content,
            })
        }
        Ok(size_written) => {
            if size_written != content.as_bytes().len() {
                return Err(Error::UnableToWriteToFile {
                    file: filename,
                    content,
                });
            }
        }
    };
    Ok(())
}

//Generate the diesel schema
pub fn generate_schema(db: &ObjectDB) -> String {
    let mut tables = String::new();
    let mut indexes = String::new();
    let mut table_list = String::new();
    for obj in db.get_objects() {
        tables = format!("{tables}\n{obj_table}", obj_table = diesel_tables(obj));
        table_list = format!("{table_list}\n    {},", obj.get_table_name());
        indexes = format!(
            "{indexes}{obj_indexes}",
            obj_indexes = diesel_joinable(obj, db)
        );
    }
    return format!("// Generated by Business DataModel Generator 2000\n{tables}\n{indexes}\ndiesel::allow_tables_to_appear_in_same_query!({table_list}\n);");
}

fn diesel_tables(obj: &Object) -> String {
    let table_name = obj.get_table_name();
    let mut attributes = String::new();
    for attribute in obj.get_attributes() {
        let column_name = attribute.get_name();
        let diesel_type = match attribute.get_type().get_base_type() {
            crate::BaseAttributeType::Integer => String::from("BigInt"),
            crate::BaseAttributeType::String => String::from("Text"),
            crate::BaseAttributeType::Reference(_refered) => String::from("Integer"),
        };
        if attribute.is_optional() {
            attributes = format!("{attributes}        {column_name} -> Nullable<{diesel_type}>,\n");
        } else {
            attributes = format!("{attributes}        {column_name} -> {diesel_type},\n");
        }
    }
    format!(
        "diesel::table! {{\n    {table_name} (id) {{\n        id -> Integer,\n{attributes}        version -> BigInt,\n    }}\n}}\n",        
    )
}

fn diesel_joinable(obj: &Object, db: &ObjectDB) -> String {
    let table_name = obj.get_table_name();
    let mut joins = String::new();
    for attribute in obj.get_attributes() {
        if let Some(refered) = attribute.get_reference() {
            let refered_object = db.get_object(&refered).unwrap();
            let refered_table = refered_object.get_table_name();
            let column_name = attribute.get_name();
            joins = format!(
                "{joins}diesel::joinable!({table_name} -> {refered_table} ({column_name}));\n"
            );
        }
    }
    joins
}
